apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: efs-pv
  resources:
    requests:
      storage: 5Gi
# ---
# apiVersion: v1
# kind: Pod
# metadata:
#   name: efs-nginx
# spec:
#   containers:
#   - name: nginx
#     image: nginx
#     volumeMounts:
#     - name: persistent-storage
#       mountPath: /usr/share/nginx/html
#   volumes:
#   - name: persistent-storage
#     persistentVolumeClaim:
#       claimName: efs-claim 
# ---
# kind: Service
# apiVersion: v1
# metadata:
#   name: nginx
# spec:
#   selector: #labels are used as selectors
#     project: expense
#     component: backend
#     environment: dev
#     version: "1.0.0"
#   ports:
#   - protocol: TCP
#     port: 80 #service port port exposed inside the cluster, Port exposed by the Service (what clients see).
#     targetPort: 80            