apiVersion: v1
kind: Pod
metadata:
  name: annotations
  annotations:                
    buildURL: "https://jenkins.com/expense/job/backend/23"
  
spec:
  containers:
  - name: nginx
    image: nginx