apiVersion: apps/v1
kind: Deployment
metadata:
  nmme: nginx
  labels: 
    app: nginx
    tier: frontend
    purpose: deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      tier: frontend
      purpose: deployment
  template:
    metadata:
      labels:
        app: nginx
        tier: frontend
        purpose: deployment
    spec: 
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80     

