apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: expense
  name: secret-reader
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pod"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
# This role binding allows "jane" to read pods in the "default" namespace.
# You need to already have a Role named "pod-reader" in that namespace.
kind: RoleBinding
metadata:
  name: secret-reader
  namespace: expense
subjects:
# You can specify more than one "subject"
- kind: ServiceAccount
  name: expense-secret  # "name" is case sensitive
  nmaespace: expense
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: Role #this must be Role or ClusterRole
  name: secret-reader # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io
---  
apiVersion: v1
kind: Pod
metadata:
  name: sa-demo
  namespace: expense
spec:
  serviceAccountName: expense-secret
  initContainers:
  - name: awscli
    image: amazon/aws-cli
    command: ['sh', '-c', 'aws secretsmanager get-secret-value --secret-id expense/mysql/credentials --query SecretString --output text > /secrets/.env']
    volumeMounts:
    - mountPath: /secrets
      name: secret-volume
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - mountPath: /secrets
      name: secret-volume
  volumes:
  - name: secret-volume
    emptyDir: {}    
  
        
    