apiVersion: v1
kind: Pod
metadata:
  name: sa-demo
  namespace: expense
spec:
  serviceAccountName: expense-secret
  initContainers:
  - name: awscli
    image: amazon/aws-cli
    command: ['sh', '-c', 'aws secretsmanager get-secret-value --secret-id expense/mysql/credentials --query SecretString --output text > /secrets/.env']
      
    volumeMounts:
    - mountPath: /secrets
      name: secret-volume
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - mountPath: /secrets
      name: secret-volume
  volumes:
  - name: secret-volume
    emptyDir: {}    
  
        
    