apiVersion: v1
kind: Pod
metadata:
  name: init-container-demo
  labels:
    app.kubernetes.io/name: MyApp
spec:
  containers:
  - name: nginx
    image: nginx
    command: ['sh', '-c', 'echo The app is running! && sleep 3600']
  initContainers:
  - name: init-myservice
    image: busybox:1.28
    command: ['sh', '-c', "for i in {1..10}; do sleep 1; if nslookup google.com; then exit 0; fi; done; exit 1"]
    
    